development:
  adapter:  postgresql
  encoding: utf8
  database: dataflux_development
  pool:     5
  username: fbruges
  password: fbruges123

production:
  adapter:  postgresql
  encoding: utf8
  database: dataflux_production
  pool:     5
  username: fbruges
  password: fbruges123
